sudo: required
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true $DOCKER_ID/react-test npm test

after_success:
    - docker build -t $DOCKER_ID/multi-client ./client
    - docker build -t $DOCKER_ID/multi-nginx ./nginx
    - docker build -t $DOCKER_ID/multi-server ./server
    - docker build -t $DOCKER_ID/multi-worker ./worker
    # Login to docker hub
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    # push images to docker hub
    - docker push $DOCKER_ID/multi-client
    - docker push $DOCKER_ID/multi-nginx
    - docker push $DOCKER_ID/multi-server
    - docker push $DOCKER_ID/multi-worker
