sudo: required
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true $DOCKER_ID/react-test npm test

after_success:
    - docker build -t $DOCKER_ID/multi-client ./client
    - docker build -t $DOCKER_ID/multi-nginx ./nginx
    - docker build -t $DOCKER_ID/multi-server ./server
    - docker build -t $DOCKER_ID/multi-worker ./worker
    # Login to docker hub
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    # push images to docker hub
    - docker push $DOCKER_ID/multi-client
    - docker push $DOCKER_ID/multi-nginx
    - docker push $DOCKER_ID/multi-server
    - docker push $DOCKER_ID/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-522309878767'
    bucket_path: 'multi-docker'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
