sudo: required
services:
    - docker

before_install:
    - docker build -t lcymburajr/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true lcymburajr/react-test npm test

after_success:
    - docker build -t lcymburajr/multi-client ./client
    - docker build -t lcymburajr/multi-nginx ./nginx
    - docker build -t lcymburajr/multi-server ./server
    - docker build -t lcymburajr/multi-worker ./worker
    # Login to docker hub
    - echo "DOCKER_PW" | docker login -u "DOCKER_ID" --password-stdin
    # push images to docker hub
    - docker push lcymburajr/multi-client
    - docker push lcymburajr/multi-nginx
    - docker push lcymburajr/multi-server
    - docker push lcymburajr/multi-worker
